[2024-05-28T14:34:34.933+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T14:34:34.957+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stored_procedures.python_task_1 manual__2024-05-28T14:29:31.227704+00:00 [queued]>
[2024-05-28T14:34:34.967+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stored_procedures.python_task_1 manual__2024-05-28T14:29:31.227704+00:00 [queued]>
[2024-05-28T14:34:34.968+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-28T14:34:34.982+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): python_task_1> on 2024-05-28 14:29:31.227704+00:00
[2024-05-28T14:34:34.989+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=468) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T14:34:34.991+0000] {standard_task_runner.py:63} INFO - Started process 474 to run task
[2024-05-28T14:34:34.992+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stored_procedures', 'python_task_1', 'manual__2024-05-28T14:29:31.227704+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/dag_example.py', '--cfg-path', '/tmp/tmpjoqxwnn1']
[2024-05-28T14:34:34.995+0000] {standard_task_runner.py:91} INFO - Job 69: Subtask python_task_1
[2024-05-28T14:34:35.049+0000] {task_command.py:426} INFO - Running <TaskInstance: stored_procedures.python_task_1 manual__2024-05-28T14:29:31.227704+00:00 [running]> on host 29c09f03cc50
[2024-05-28T14:34:35.142+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yamin' AIRFLOW_CTX_DAG_ID='stored_procedures' AIRFLOW_CTX_TASK_ID='python_task_1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T14:29:31.227704+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T14:29:31.227704+00:00'
[2024-05-28T14:34:35.144+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T14:34:35.160+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T14:34:35.161+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_example.py", line 41, in create_mew_total_tables
    driver_standings = pd.read_csv(csv_file_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './dags/csv/driver_standings.csv'
[2024-05-28T14:34:35.180+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=stored_procedures, task_id=python_task_1, execution_date=20240528T142931, start_date=20240528T143434, end_date=20240528T143435
[2024-05-28T14:34:35.195+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 69 for task python_task_1 ([Errno 2] No such file or directory: './dags/csv/driver_standings.csv'; 474)
[2024-05-28T14:34:35.206+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-28T14:34:35.223+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T14:34:35.225+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
