[2024-05-28T14:35:14.998+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T14:35:15.021+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stored_procedures.python_task_1 manual__2024-05-28T14:30:10.800852+00:00 [queued]>
[2024-05-28T14:35:15.031+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stored_procedures.python_task_1 manual__2024-05-28T14:30:10.800852+00:00 [queued]>
[2024-05-28T14:35:15.032+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-28T14:35:15.048+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): python_task_1> on 2024-05-28 14:30:10.800852+00:00
[2024-05-28T14:35:15.055+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=488) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T14:35:15.057+0000] {standard_task_runner.py:63} INFO - Started process 494 to run task
[2024-05-28T14:35:15.057+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stored_procedures', 'python_task_1', 'manual__2024-05-28T14:30:10.800852+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/dag_example.py', '--cfg-path', '/tmp/tmpciv42ofi']
[2024-05-28T14:35:15.060+0000] {standard_task_runner.py:91} INFO - Job 74: Subtask python_task_1
[2024-05-28T14:35:15.117+0000] {task_command.py:426} INFO - Running <TaskInstance: stored_procedures.python_task_1 manual__2024-05-28T14:30:10.800852+00:00 [running]> on host 29c09f03cc50
[2024-05-28T14:35:15.207+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yamin' AIRFLOW_CTX_DAG_ID='stored_procedures' AIRFLOW_CTX_TASK_ID='python_task_1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T14:30:10.800852+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T14:30:10.800852+00:00'
[2024-05-28T14:35:15.209+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T14:35:15.224+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T14:35:15.225+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_example.py", line 41, in create_mew_total_tables
    driver_standings = pd.read_csv(csv_file_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './dags/csv/driver_standings.csv'
[2024-05-28T14:35:15.240+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=stored_procedures, task_id=python_task_1, execution_date=20240528T143010, start_date=20240528T143515, end_date=20240528T143515
[2024-05-28T14:35:15.252+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 74 for task python_task_1 ([Errno 2] No such file or directory: './dags/csv/driver_standings.csv'; 494)
[2024-05-28T14:35:15.272+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-28T14:35:15.291+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T14:35:15.293+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
