[2024-05-28T14:29:35.537+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T14:29:35.566+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stored_procedures.python_task_2 manual__2024-05-28T14:29:31.227704+00:00 [queued]>
[2024-05-28T14:29:35.576+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stored_procedures.python_task_2 manual__2024-05-28T14:29:31.227704+00:00 [queued]>
[2024-05-28T14:29:35.577+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-28T14:29:35.596+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): python_task_2> on 2024-05-28 14:29:31.227704+00:00
[2024-05-28T14:29:35.606+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=273) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T14:29:35.607+0000] {standard_task_runner.py:63} INFO - Started process 282 to run task
[2024-05-28T14:29:35.608+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stored_procedures', 'python_task_2', 'manual__2024-05-28T14:29:31.227704+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dag_example.py', '--cfg-path', '/tmp/tmpg9yewefh']
[2024-05-28T14:29:35.610+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask python_task_2
[2024-05-28T14:29:35.671+0000] {task_command.py:426} INFO - Running <TaskInstance: stored_procedures.python_task_2 manual__2024-05-28T14:29:31.227704+00:00 [running]> on host 29c09f03cc50
[2024-05-28T14:29:35.765+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yamin' AIRFLOW_CTX_DAG_ID='stored_procedures' AIRFLOW_CTX_TASK_ID='python_task_2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T14:29:31.227704+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T14:29:31.227704+00:00'
[2024-05-28T14:29:35.766+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T14:29:35.863+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T14:29:35.864+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_example.py", line 75, in execute_query_with_psycopg
    driver_standings_total = pd.read_csv(driver_standings_total_path)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './dags/csv/driver_standings_total.csv'
[2024-05-28T14:29:35.877+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=stored_procedures, task_id=python_task_2, execution_date=20240528T142931, start_date=20240528T142935, end_date=20240528T142935
[2024-05-28T14:29:35.889+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task python_task_2 ([Errno 2] No such file or directory: './dags/csv/driver_standings_total.csv'; 282)
[2024-05-28T14:29:35.903+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-28T14:29:35.929+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T14:29:35.932+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
