[2024-05-28T15:53:49.254+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: stored_procedures.update_driver_nationality manual__2024-05-28T15:53:47.276075+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
