[2024-05-28T14:37:07.723+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-28T14:37:07.742+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stored_procedures.python_task_2 manual__2024-05-28T14:32:02.507511+00:00 [queued]>
[2024-05-28T14:37:07.749+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stored_procedures.python_task_2 manual__2024-05-28T14:32:02.507511+00:00 [queued]>
[2024-05-28T14:37:07.750+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-28T14:37:07.760+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): python_task_2> on 2024-05-28 14:32:02.507511+00:00
[2024-05-28T14:37:07.769+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=528) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-28T14:37:07.771+0000] {standard_task_runner.py:63} INFO - Started process 530 to run task
[2024-05-28T14:37:07.770+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stored_procedures', 'python_task_2', 'manual__2024-05-28T14:32:02.507511+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/dag_example.py', '--cfg-path', '/tmp/tmp19gjq9id']
[2024-05-28T14:37:07.773+0000] {standard_task_runner.py:91} INFO - Job 79: Subtask python_task_2
[2024-05-28T14:37:07.819+0000] {task_command.py:426} INFO - Running <TaskInstance: stored_procedures.python_task_2 manual__2024-05-28T14:32:02.507511+00:00 [running]> on host 29c09f03cc50
[2024-05-28T14:37:07.898+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yamin' AIRFLOW_CTX_DAG_ID='stored_procedures' AIRFLOW_CTX_TASK_ID='python_task_2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-28T14:32:02.507511+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-28T14:32:02.507511+00:00'
[2024-05-28T14:37:07.900+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-28T14:37:07.984+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-28T14:37:07.985+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_example.py", line 66, in execute_query_with_psycopg
    cur.execute("CREATE SCHEMA airflow11133;")
psycopg2.errors.DuplicateSchema: schema "***11133" already exists

[2024-05-28T14:37:07.997+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=stored_procedures, task_id=python_task_2, execution_date=20240528T143202, start_date=20240528T143707, end_date=20240528T143707
[2024-05-28T14:37:08.007+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 79 for task python_task_2 (schema "***11133" already exists
; 530)
[2024-05-28T14:37:08.026+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-28T14:37:08.045+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-28T14:37:08.049+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
